// Curated Phosphor registry — only the icons the design uses, so the bundle
// stays lean. Add an icon here once, reference it by name everywhere.
import {
  ArrowRightIcon,
  ArrowsClockwiseIcon,
  BatteryFullIcon,
  BellIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpDownIcon,
  CameraIcon,
  CarProfileIcon,
  CellSignalFullIcon,
  CheckIcon,
  CheckCircleIcon,
  CircleIcon,
  ClockIcon,
  CreditCardIcon,
  CrownSimpleIcon,
  DeviceMobileIcon,
  EnvelopeSimpleIcon,
  ExportIcon,
  FilePdfIcon,
  GaugeIcon,
  GearSixIcon,
  GlobeIcon,
  ImageIcon,
  InfoIcon,
  ListChecksIcon,
  LockSimpleIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  MoneyIcon,
  PackageIcon,
  PaperclipIcon,
  PaperPlaneTiltIcon,
  PauseIcon,
  PercentIcon,
  PhoneIcon,
  PhoneCallIcon,
  PlayIcon,
  PlusIcon,
  QuestionIcon,
  ReceiptIcon,
  SealCheckIcon,
  ShieldCheckIcon,
  ShoppingCartSimpleIcon,
  SignOutIcon,
  SlidersHorizontalIcon,
  SmileyIcon,
  SquaresFourIcon,
  StorefrontIcon,
  UserIcon,
  UserCircleIcon,
  UsersThreeIcon,
  WhatsappLogoIcon,
  WifiHighIcon,
  WarningCircleIcon,
  WrenchIcon,
  XIcon,
  XCircleIcon,
  type IconProps,
  type IconWeight,
} from "phosphor-react-native";
import { C } from "@/lib/theme";

const REGISTRY = {
  "arrow-right": ArrowRightIcon,
  "arrows-clockwise": ArrowsClockwiseIcon,
  "battery-full": BatteryFullIcon,
  bell: BellIcon,
  "caret-left": CaretLeftIcon,
  "caret-right": CaretRightIcon,
  "caret-up-down": CaretUpDownIcon,
  "car-profile": CarProfileIcon,
  "cell-signal-full": CellSignalFullIcon,
  check: CheckIcon,
  "check-circle": CheckCircleIcon,
  circle: CircleIcon,
  clock: ClockIcon,
  "credit-card": CreditCardIcon,
  "crown-simple": CrownSimpleIcon,
  "device-mobile": DeviceMobileIcon,
  "envelope-simple": EnvelopeSimpleIcon,
  export: ExportIcon,
  "file-pdf": FilePdfIcon,
  gauge: GaugeIcon,
  "gear-six": GearSixIcon,
  globe: GlobeIcon,
  image: ImageIcon,
  camera: CameraIcon,
  info: InfoIcon,
  "list-checks": ListChecksIcon,
  "lock-simple": LockSimpleIcon,
  search: MagnifyingGlassIcon,
  microphone: MicrophoneIcon,
  money: MoneyIcon,
  package: PackageIcon,
  paperclip: PaperclipIcon,
  "paper-plane-tilt": PaperPlaneTiltIcon,
  pause: PauseIcon,
  percent: PercentIcon,
  phone: PhoneIcon,
  "phone-call": PhoneCallIcon,
  play: PlayIcon,
  plus: PlusIcon,
  question: QuestionIcon,
  receipt: ReceiptIcon,
  "seal-check": SealCheckIcon,
  "shield-check": ShieldCheckIcon,
  cart: ShoppingCartSimpleIcon,
  "sign-out": SignOutIcon,
  sliders: SlidersHorizontalIcon,
  smiley: SmileyIcon,
  "squares-four": SquaresFourIcon,
  storefront: StorefrontIcon,
  user: UserIcon,
  "user-circle": UserCircleIcon,
  "users-three": UsersThreeIcon,
  whatsapp: WhatsappLogoIcon,
  "wifi-high": WifiHighIcon,
  wrench: WrenchIcon,
  "warning-circle": WarningCircleIcon,
  x: XIcon,
  "x-circle": XCircleIcon,
} as const;

export type IconName = keyof typeof REGISTRY;

type Props = {
  name: IconName;
  size?: number;
  color?: string;
  weight?: IconWeight;
} & Omit<IconProps, "color" | "size" | "weight">;

export function Icon({ name, size = 20, color = C.ink, weight = "regular", ...rest }: Props) {
  const Cmp = REGISTRY[name];
  return <Cmp size={size} color={color} weight={weight} {...rest} />;
}
